# def foo():
#     print('in foo')
#     boo()
#
# def boo():
#     print('in boo')
# foo()

print("*******************************************************")
# def foo():
#     print('in foo')
#     boo()
#
# foo() #错误
#
# def boo():
#     print('in boo')
"""
在执行了一个调用了其他函数的函数时，如果在内存中还没有找到被条用函数的定义，则程序会报错
"""
print("*******************************************************")